// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDglpwrg4X21ZJpQy1RB-EizQ34Gmnxo7g',
    appId: '1:588790003051:web:c9d7f2cb5c3db15ae6882e',
    messagingSenderId: '588790003051',
    projectId: 'heladeria-75460',
    authDomain: 'heladeria-75460.firebaseapp.com',
    storageBucket: 'heladeria-75460.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2ssbEklIuVXZHuZo7MtwmI8lPz3lGZk',
    appId: '1:588790003051:android:eb4636cfe8a92243e6882e',
    messagingSenderId: '588790003051',
    projectId: 'heladeria-75460',
    storageBucket: 'heladeria-75460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBygi0gfgv_wXxqZ-YKHOGbBYagTrAqYHM',
    appId: '1:588790003051:ios:628d563fc36b19fde6882e',
    messagingSenderId: '588790003051',
    projectId: 'heladeria-75460',
    storageBucket: 'heladeria-75460.appspot.com',
    iosClientId: '588790003051-07ail0m27ot0lulfe9l9ba1cm06b5can.apps.googleusercontent.com',
    iosBundleId: 'com.heladeriasyst.systemDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBygi0gfgv_wXxqZ-YKHOGbBYagTrAqYHM',
    appId: '1:588790003051:ios:628d563fc36b19fde6882e',
    messagingSenderId: '588790003051',
    projectId: 'heladeria-75460',
    storageBucket: 'heladeria-75460.appspot.com',
    iosClientId: '588790003051-07ail0m27ot0lulfe9l9ba1cm06b5can.apps.googleusercontent.com',
    iosBundleId: 'com.heladeriasyst.systemDelivery',
  );
}
